version: "3.0"

services:

  mysql:
    labels:
      - "traefik.enable=false"
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./mysql/init.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  gateway:
    build:
      context: ./services/gateway.service
    image: gateway
    env_file: docker-compose.env
    environment:
      SERVICES: gateway
      PORT: 80
    entrypoint: forever
    command: --plain --minUptime 1000 --spinSleepTime 4000 --watchDirectory /home/app/src -w src/main.js
    volumes:
      - ./services/gateway.service/src:/home/app/src
    depends_on:
      - rabbit
      - auth
    labels:
      - "traefik.enable=true"   
      - "traefik.backend=gateway"
      - "traefik.port=3001"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
    ports:
      - "4800:80"

  auth:
    build:
      context: ./services/auth.service
    image: auth
    env_file: docker-compose.env
    environment:
      SERVICES: auth
      PORT: 80
      MYSQL_DATABASE: "users"
    entrypoint: forever
    command: --plain --minUptime 1000 --spinSleepTime 4000 --watchDirectory /home/app/src -w src/main.js
    volumes:
      - ./services/auth.service/src:/home/app/src
    depends_on:
      - mysql
      - rabbit

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "3000:80"
      - "3001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
