version: "3.0"

services:

  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./mysql/init.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  gateway:
    build:
      context: ./services/gateway.service
    image: gateway
    env_file: docker-compose.env
    environment:
      SERVICES: gateway
      PORT: 80
    entrypoint: forever
    command: --plain --minUptime 1000 --spinSleepTime 4000 --watchDirectory /home/app/src -w src/main.js
    volumes:
      - ./services/gateway.service/src:/home/app/src
    depends_on:
      - rabbit
      - auth
      - shoppingcentreasset
    ports:
      - "4800:80"

  auth:
    build:
      context: ./services/auth.service
    image: auth
    env_file: docker-compose.env
    environment:
      SERVICES: auth
      PORT: 80
      MYSQL_DATABASE: "users"
    entrypoint: forever
    command: --plain --minUptime 1000 --spinSleepTime 4000 --watchDirectory /home/app/src -w src/main.js
    volumes:
      - ./services/auth.service/src:/home/app/src
    depends_on:
      - mysql
      - rabbit
      - auditlog

  shoppingcentreasset:
    build:
      context: ./services/shoppingCentreAsset.service
    image: shoppingcentreasset
    env_file: docker-compose.env
    environment:
      SERVICES: shoppingcentreasset
      PORT: 80
      MYSQL_DATABASE: "shoppingCentreAsset"
    entrypoint: forever
    command: --plain --minUptime 1000 --spinSleepTime 4000 --watchDirectory /home/app/src -w src/main.js
    volumes:
      - ./services/shoppingCentreAsset.service/src:/home/app/src
    depends_on:
      - mysql
      - rabbit
      - auditlog

  auditlog:
    build: 
      context: ./services/auditLog.service
    image: auditlog
    env_file: docker-compose.env
    environment:
      SERVICES: auditlog
      PORT: 80
    entrypoint: forever
    command: --plain --minUptime 1000 --spinSleepTime 4000 --watchDirectory /home/app/src -w src/main.js
    volumes:
      - ./services/auditLog.service/src:/home/app/src
    depends_on:
      - elasticsearch
      - rabbit
