FLUSH PRIVILEGES;
GRANT CREATE, SELECT, INSERT, UPDATE, DELETE ON `users`.* TO `root`;
GRANT CREATE, SELECT, INSERT, UPDATE, DELETE ON `shoppingCentreAsset`.* TO `root`;
GRANT CREATE, SELECT, INSERT, UPDATE, DELETE ON `Asset`.* TO `root`;
CREATE DATABASE IF NOT EXISTS `users` DEFAULT CHARACTER SET utf8;;
CREATE DATABASE IF NOT EXISTS `shoppingCentreAsset` DEFAULT CHARACTER SET utf8;;
